# Generated by Django 4.2.28 on 2026-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('education', models.TextField(blank=True)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('projects', models.ManyToManyField(blank=True, related_name='profiles', to='api.project')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='api.skill')),
            ],
        ),
    ]
